import * as XLSX from 'xlsx'
import type { ImportRow, PriceRow } from '../types'
import { inferStyle, normalizeStyle } from './normalize'
type CellValue=string|number|boolean|null
type Mapping={group?:number;style:number;bulk:number[];option?:number;remark?:number;headerRow:number}
const clean=(v:unknown)=>String(v??'').toUpperCase().replace(/\n/g,' ').replace(/\s+/g,' ').replace(/\s*\(\s*/g,' (').replace(/\s*\)\s*/g,')').trim()
const styles=['STYLE','STYLE#','STYLE NAME'];const groups=['PRODUCT','PRODUCT GROUP'];const options=['SUBLIMATION TYPE','PRICE OPTION'];const remarks=['REMARK','REMARKS','NOTE','NOTES']
export function detectTables(grid:CellValue[][]):Mapping[]{const out:Mapping[]=[];grid.forEach((line,headerRow)=>{const h=line.map(clean);const style=h.findIndex(x=>styles.includes(x));if(style<0)return;const bulk:number[]=[];h.forEach((x,c)=>{if(x==='FOB'||x==='FOB (BULK)'||x==='BULK FOB'||x==='BULK')bulk.push(c)});if(!bulk.length)return;const at=(a:string[])=>{const i=h.findIndex(x=>a.includes(x));return i<0?undefined:i};out.push({style,bulk,group:at(groups),option:at(options),remark:at(remarks),headerRow})});return out}
export const numberValue=(cell:XLSX.CellObject|undefined):number|null=>{const n=typeof cell?.v==='number'?cell.v:Number(String(cell?.v??'').replace(/[$,]/g,'').trim());return Number.isFinite(n)&&n>0?n:null}
function merged(sheet:XLSX.WorkSheet,row:number,col:number|undefined){if(col==null)return '';const own=sheet[XLSX.utils.encode_cell({r:row,c:col})]?.v;if(own!=null&&String(own).trim())return String(own).trim();const m=(sheet['!merges']??[]).find(x=>col>=x.s.c&&col<=x.e.c&&row>=x.s.r&&row<=x.e.r);return m?String(sheet[XLSX.utils.encode_cell(m.s)]?.v??'').trim():''}
const recognizedOption=(value:string)=>{const v=value.trim().toUpperCase();return v==='ROLLER'?'Roller':v==='DIGITAL'?'Digital':''}
export function parseWorkbook(data:ArrayBuffer,filename:string):ImportRow[]{const wb=XLSX.read(data,{type:'array',cellFormula:true,cellText:true});const rows:ImportRow[]=[];for(const sheetName of wb.SheetNames){const sheet=wb.Sheets[sheetName];const range=XLSX.utils.decode_range(sheet['!ref']||'A1');const grid=XLSX.utils.sheet_to_json<CellValue[]>(sheet,{header:1,raw:true,defval:null,range:{s:{r:0,c:0},e:range.e}});const tables=detectTables(grid);tables.forEach((m,i)=>{const end=tables[i+1]?.headerRow??grid.length;for(let r=m.headerRow+1;r<end;r++){const display_name=merged(sheet,r,m.style);if(!display_name||styles.includes(clean(display_name)))continue;const prices=[...new Set(m.bulk.map(c=>numberValue(sheet[XLSX.utils.encode_cell({r,c})])).filter((x):x is number=>x!=null))];if(!prices.length)continue;const product_group=merged(sheet,r,m.group);let rawOption=merged(sheet,r,m.option);let remark=m.remark==null?'':String(grid[r]?.[m.remark]??'').trim();if(!rawOption&&recognizedOption(remark)){rawOption=remark;remark=''}const option=recognizedOption(rawOption)||rawOption.trim()||'Standard';const inferred=inferStyle(display_name,product_group);const conflict=prices.length>1;rows.push({key:`${sheetName}:${r+1}:${i}`,sheet:sheetName,row:r+1,import:!conflict,status:conflict?'Needs Decision':'New',message:conflict?'Select one incoming Bulk FOB.':'',display_name,normalized_name:normalizeStyle(display_name),...inferred,product_group,price_option:option,bulk_fob:prices.length===1?prices[0]:null,internal_remark:remark,public_remark_en:[...remark].some(c=>c.charCodeAt(0)>127)?'':remark,change_reason:'',effective_date:new Date().toISOString().slice(0,10),source_type:'EXCEL',source_file:filename,source_sheet:sheetName,source_row:r+1,bulkCandidates:prices})}})}return mergeImports(rows)}
export function mergeImports(input:ImportRow[],existing:PriceRow[]=[]):ImportRow[]{const grouped=new Map<string,ImportRow[]>();input.forEach(r=>{const k=`${r.normalized_name}\0${r.price_option.toLowerCase()}`;grouped.set(k,[...(grouped.get(k)??[]),r])});return [...grouped.values()].map(group=>{const first={...group[0]};const prices=[...new Set(group.flatMap(r=>r.bulkCandidates??(r.bulk_fob==null?[]:[r.bulk_fob])))];first.bulkCandidates=prices;if(prices.length!==1)return {...first,bulk_fob:null,status:'Needs Decision',import:false,message:`Conflicting incoming prices: ${prices.join(', ')}`};first.bulk_fob=prices[0];const current=existing.find(r=>r.normalized_name===first.normalized_name&&r.price_option.toLowerCase()===first.price_option.toLowerCase());if(current){first.current_bulk_fob=current.bulk_fob;first.current_updated_at=current.updated_at;const same=current.bulk_fob===first.bulk_fob;first.status=same?'Unchanged':'Update';first.import=true;first.message=same?'No price change.':'Select a change reason before import.'}else first.status=group.length>1?'Duplicate':'New';return first})}
