import{useEffect,useState}from'react'
import{adminHeaders}from'../lib/supabase'
import type{ShareLink}from'../types'
export function ShareAdminPage(){
 const[links,setLinks]=useState<ShareLink[]>([]),[label,setLabel]=useState(''),[expires,setExpires]=useState(''),[error,setError]=useState('')
 const load=async()=>{setError('');const r=await fetch('/api/admin/share',{headers:await adminHeaders(),cache:'no-store'});if(r.ok)setLinks(await r.json());else setError('공유 링크 목록을 불러오지 못했습니다.')};useEffect(()=>{void load()},[])
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');const r=await fetch('/api/admin/share',{method:'POST',headers:await adminHeaders(),body:JSON.stringify({label,expires_at:expires?new Date(expires).toISOString():null})}),body=await r.json();if(r.ok){setLabel('');setExpires('');void load()}else setError(body.error)}
 const revoke=async(id:string)=>{if(confirm('이 링크를 해제할까요?')){const r=await fetch(`/api/admin/share/${id}`,{method:'DELETE',headers:await adminHeaders()});if(!r.ok)setError('링크를 해제하지 못했습니다.');else void load()}},state=(l:ShareLink)=>l.revoked_at?'해제':l.expires_at&&new Date(l.expires_at)<=new Date()?'만료':'활성'
 return <main className="container admin"><header><p className="eyebrow">READ-ONLY ACCESS</p><h1>공유 링크 관리</h1><p className="muted">새 링크는 암호화되어 관리자만 다시 확인할 수 있습니다.</p></header><form className="card share-form" onSubmit={create}><label>링크 이름<input required value={label} onChange={e=>setLabel(e.target.value)}/></label><label>만료일 (선택)<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><button className="primary">링크 생성</button></form>{error&&<p role="alert" className="error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>이름</th><th>생성일</th><th>마지막 확인</th><th>만료일</th><th>상태</th><th>활성 링크 URL</th><th>Action</th></tr></thead><tbody>{links.map(l=><tr key={l.id}><td>{l.label}</td><td>{new Date(l.created_at).toLocaleString()}</td><td>{l.last_accessed_at?new Date(l.last_accessed_at).toLocaleString():'확인 기록 없음'}</td><td>{l.expires_at?new Date(l.expires_at).toLocaleString():'없음'}</td><td><span className="badge">{state(l)}</span></td><td>{l.original_url_available&&l.link?<><input aria-label={`${l.label} URL`} readOnly value={l.link}/><button onClick={()=>navigator.clipboard.writeText(l.link!)}>링크 복사</button> <button onClick={()=>window.open(l.link,'_blank','noopener')}>공유 화면 열기</button></>:<><span className="error">기존 링크 주소를 복원할 수 없습니다. 한 번만 링크를 재생성해 주세요.</span> <button onClick={()=>{setLabel(`${l.label} (재생성)`);window.scrollTo({top:0,behavior:'smooth'})}}>링크 재생성</button></>}</td><td><button disabled={state(l)!=='활성'} onClick={()=>revoke(l.id)}>링크 해제</button></td></tr>)}</tbody></table></div></main>
}
