import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { PriceTable } from '../components/PriceTable'
import { matchesSearch } from '../lib/normalize'
import type { PriceRow } from '../types'

export function SharePage() { const { token } = useParams(); const [rows,setRows]=useState<PriceRow[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [season,setSeason]=useState(''); const [item,setItem]=useState(''); const [priced,setPriced]=useState('all'); const [sort,setSort]=useState('new')
  useEffect(() => { fetch(`/api/share/${encodeURIComponent(token ?? '')}`, { cache: 'no-store' }).then(async r => { if (!r.ok) throw new Error((await r.json()).error); return r.json() }).then(setRows).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [token])
  const filtered = useMemo(() => rows.filter(r => matchesSearch(r,query) && (!season || r.season===season) && (!item || r.item_type===item) && (priced==='all' || priced==='both' && r.bulk_fob!=null && r.sample_fob!=null || priced==='missing' && (r.bulk_fob==null || r.sample_fob==null))).sort((a,b) => sort==='style' ? a.display_name.localeCompare(b.display_name) : (Number(b.season)-Number(a.season))*(sort==='old'?-1:1)), [rows,query,season,item,priced,sort])
  return <main className="container share"><header><p className="eyebrow">READ-ONLY PRICE DIRECTORY</p><h1>FLY RACING – Confirmed FOB Price List</h1><p className="muted">현재 적용 중인 최종 FOB 가격입니다.</p></header><section className="filters card"><label className="search">검색<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Style, season, item, remark" /></label><label>Season<select value={season} onChange={e=>setSeason(e.target.value)}><option value="">All</option>{[...new Set(rows.map(r=>r.season))].sort((a,b)=>Number(b)-Number(a)).map(x=><option key={x}>{x}</option>)}</select></label><label>Item<select value={item} onChange={e=>setItem(e.target.value)}><option value="">All</option>{['PANT','JERSEY','GLOVE','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label>Price<select value={priced} onChange={e=>setPriced(e.target.value)}><option value="all">All</option><option value="both">Both prices</option><option value="missing">Missing price</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Latest season</option><option value="old">Oldest season</option><option value="style">Style name</option></select></label></section>{loading ? <div className="state">가격을 불러오는 중…</div> : error ? <div className="state error">{error}</div> : <><p className="result-count"><strong>{filtered.length}</strong> results</p><PriceTable rows={filtered}/></>}</main> }
