import { useEffect, useState } from 'react'
import type { ItemType, PriceRow } from '../types'
import { inferStyle, normalizeStyle } from '../lib/normalize'
import { supabase } from '../lib/supabase'

const blank = (): PriceRow => ({ display_name: '', normalized_name: '', season: '', item_type: 'OTHER', bulk_fob: null, sample_fob: null, remark: '', effective_date: new Date().toISOString().slice(0, 10), source_type: 'KEY_IN' })
export function PriceForm({ initial, onSaved, onCancel }: { initial?: PriceRow; onSaved: () => void; onCancel?: () => void }) {
  const [form, setForm] = useState<PriceRow>(initial ? { ...initial, remark: '' } : blank()); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => setForm(initial ? { ...initial, remark: '' } : blank()), [initial])
  const style = (display_name: string) => setForm((f) => ({ ...f, display_name, normalized_name: normalizeStyle(display_name), ...inferStyle(display_name) }))
  const save = async (e: React.FormEvent) => { e.preventDefault(); setError(''); if (form.bulk_fob == null && form.sample_fob == null) return setError('Bulk FOB와 Sample FOB 중 하나는 필수입니다.'); if (initial && !form.remark.trim()) return setError('기존 가격 변경 시 Remark가 필요합니다.'); setBusy(true); const { error: err } = await supabase.rpc('save_price', { p: { ...form, normalized_name: normalizeStyle(form.display_name) } }); setBusy(false); if (err) setError(err.message); else { setForm(blank()); onSaved() } }
  return <form className="card form-grid" onSubmit={save}><label>Style<input required value={form.display_name} onChange={(e) => style(e.target.value)} placeholder="27 LITE GLOVE" /></label><label>Season<input required pattern="\d{2}(\.5)?" value={form.season} onChange={(e) => setForm({ ...form, season: e.target.value })} /></label><label>Item Type<select value={form.item_type} onChange={(e) => setForm({ ...form, item_type: e.target.value as ItemType })}>{['PANT','JERSEY','GLOVE','OTHER'].map((x) => <option key={x}>{x}</option>)}</select></label><label>Bulk FOB<input type="number" min="0.0001" step="0.0001" value={form.bulk_fob ?? ''} onChange={(e) => setForm({ ...form, bulk_fob: e.target.value ? Number(e.target.value) : null })} /></label><label>Sample FOB<input type="number" min="0.0001" step="0.0001" value={form.sample_fob ?? ''} onChange={(e) => setForm({ ...form, sample_fob: e.target.value ? Number(e.target.value) : null })} /></label><label>Effective Date<input required type="date" value={form.effective_date} onChange={(e) => setForm({ ...form, effective_date: e.target.value })} /></label><label className="wide">Remark<textarea value={form.remark} onChange={(e) => setForm({ ...form, remark: e.target.value })} placeholder={initial ? '가격 변경 사유 (필수)' : '선택 사항'} /></label>{error && <p className="error wide">{error}</p>}<div className="wide form-actions"><button className="primary" disabled={busy}>{busy ? '저장 중…' : initial ? '신규 가격 버전 저장' : '가격 저장'}</button>{onCancel && <button type="button" onClick={onCancel}>취소</button>}</div></form>
}
