import{useEffect,useState}from'react'
import type{ChangeReason,ItemType,PriceRow}from'../types'
import{inferStyle,normalizeStyle}from'../lib/normalize'
import{saveManualPrice,type SavedManualPrice}from'../lib/manualPrice'
const blank=():PriceRow=>({display_name:'',normalized_name:'',season:'',item_type:'OTHER',product_group:'',price_option:'Standard',bulk_fob:null,internal_remark:'',public_remark_en:'',change_reason:'',effective_date:new Date().toISOString().slice(0,10),source_type:'KEY_IN'})
const editForm=(initial:PriceRow):PriceRow=>({...initial,source_type:'KEY_IN',internal_remark:'',public_remark_en:'',change_reason:''})
export function PriceForm({initial,onSaved,onCancel}:{initial?:PriceRow;onSaved:(saved:SavedManualPrice)=>Promise<void>;onCancel?:()=>void}){
 const[form,setForm]=useState<PriceRow>(initial?editForm(initial):blank()),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>setForm(initial?editForm(initial):blank()),[initial])
 const style=(display_name:string)=>setForm(f=>({...f,display_name,normalized_name:normalizeStyle(display_name),...inferStyle(display_name,f.product_group)}))
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(form.bulk_fob==null)return setError('Bulk FOB는 필수입니다.');if(initial&&!form.change_reason)return setError('가격 변경 사유를 선택하세요.');if(form.change_reason==='OTHER'&&!form.public_remark_en.trim())return setError('기타 사유에는 Public Remark (English)가 필수입니다.');setBusy(true);try{const saved=await saveManualPrice(form);await onSaved(saved);setForm(blank())}catch(reason){setError(reason instanceof Error?reason.message:'가격을 저장하지 못했습니다.')}finally{setBusy(false)}}
 return <form className="card form-grid" onSubmit={save}><label>Style<input required value={form.display_name} onChange={e=>style(e.target.value)}/></label><label>Season<input required pattern="\d{2}(\.5)?" value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/></label><label>Item Type<select value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value as ItemType})}>{['PANT','JERSEY','GLOVE','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label>Product Group<input required value={form.product_group} onChange={e=>setForm({...form,product_group:e.target.value,...inferStyle(form.display_name,e.target.value)})}/></label><label>Price Option<input required value={form.price_option} onChange={e=>setForm({...form,price_option:e.target.value})}/></label><label>Bulk FOB<input required type="number" min=".0001" step=".0001" value={form.bulk_fob??''} onChange={e=>setForm({...form,bulk_fob:e.target.value?Number(e.target.value):null})}/></label><label>Effective Date<input required type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label>{initial&&<label>변경 사유<select required value={form.change_reason} onChange={e=>setForm({...form,change_reason:e.target.value as ChangeReason})}><option value="">선택</option><option value="TYPO">오타 수정</option><option value="MATERIAL">자재단가 변경</option><option value="LABOR">공임 변경</option><option value="SPECIFICATION">사양 변경</option><option value="OTHER">기타</option></select></label>}<label className="wide">Internal Remark<textarea value={form.internal_remark} onChange={e=>setForm({...form,internal_remark:e.target.value})}/></label><label className="wide">Public Remark (English)<textarea lang="en" value={form.public_remark_en} onChange={e=>setForm({...form,public_remark_en:e.target.value})}/></label>{error&&<p role="alert" className="error wide">{error}</p>}<div className="wide form-actions"><button className="primary" disabled={busy}>{busy?'저장 및 DB 확인 중…':initial?'신규 가격 버전 저장':'가격 저장'}</button>{onCancel&&<button type="button" onClick={onCancel}>취소</button>}</div></form>
}
